//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIOHANG
    {
        public string ID { get; set; }
        public string TENSP { get; set; }
        public string GIA { get; set; }
        public string THETICH { get; set; }
        public string MOTA { get; set; }
        public string TONGTIEN { get; set; }
        public string DIACHI { get; set; }
        public string ANH { get; set; }
        public string MAMAU { get; set; }
        public Nullable<System.DateTime> HSD { get; set; }
        public Nullable<bool> TRANGTHAI { get; set; }
        public string MASP { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
