//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADON()
        {
            this.CTHOADONs = new HashSet<CTHOADON>();
        }
    
        public int MAHD { get; set; }
        public Nullable<System.DateTime> NGAYLAP { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<double> GIA { get; set; }
        public Nullable<double> TONGTIEN { get; set; }
        public string MANV { get; set; }
        public Nullable<int> MAKH { get; set; }
        public string MATK { get; set; }
        public string DIACHI { get; set; }
        public string MAMAU { get; set; }
        public Nullable<bool> TRANGTHAI { get; set; }
        public string MOTA { get; set; }
        public string PHUONGTHUCTT { get; set; }
        public string THETICH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHOADON> CTHOADONs { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual THONGKE THONGKE { get; set; }
    }
}
