//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CTHOADONs = new HashSet<CTHOADON>();
            this.GIOHANGs = new HashSet<GIOHANG>();
            this.imgcons = new HashSet<imgcon>();
        }
    
        public string MASP { get; set; }
        public string TENSP { get; set; }
        public Nullable<double> GIA { get; set; }
        public string THETICH { get; set; }
        public Nullable<bool> TRANGTHAI { get; set; }
        public string MOTA { get; set; }
        public string MLSP { get; set; }
        public string CAPDO { get; set; }
        public string MAMAU { get; set; }
        public string ANH { get; set; }
        public Nullable<System.DateTime> HSD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHOADON> CTHOADONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIOHANG> GIOHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<imgcon> imgcons { get; set; }
        public virtual LOAISP LOAISP { get; set; }
    }
}
