//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TINTUC
    {
        public string ID { get; set; }
        public string MOTA { get; set; }
        public Nullable<System.DateTime> NGAYDANG { get; set; }
        public string ANH { get; set; }
        public string TIEUDE { get; set; }
        public Nullable<bool> TRANGTHAI { get; set; }
    }
}
