//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHOPSON.Areas.ADMIN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class imgcon
    {
        public string ID { get; set; }
        public string MASP { get; set; }
        public string IMG1 { get; set; }
        public string IMG2 { get; set; }
        public string IMG3 { get; set; }
        public string IMG4 { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
