//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHOPSON.Areas.ADMIN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONGKE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THONGKE()
        {
            this.HOADONs = new HashSet<HOADON>();
        }
    
        public string MATK { get; set; }
        public string NGAYLAP { get; set; }
        public string TONGSPBAN { get; set; }
        public string TONGTIENBAN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs { get; set; }
    }
}
